### ISSUE TITLE
理解和问题

### ISSUE THREAD

**Issue by Zhangxu0501** [chenkovsky/pyhql#1]
先说明一些我的情况，学过python，基础一般，没学到过面向对象部分，但我懂得java的面向对象的部分，正在慢慢转换。
我看懂了ddl.py 和 example.py
ddl.py是用来描述数据的，按照数据类型对一行数据拆分，以便后续条件化查询。
example.py 以一个人的数据为例，细分为年ID、龄段、性别、去过的城市四个字段。通过data以及几个函数，将这四个字段赋给example对象的一个实例。
这两段代码将数据抽取为我们需要的对象类型。
不知道这样理解哪里有问题？

还有就是大家都用什么IDE呢？我一直是用的pythonX,Y写小程序，我想我需要一个新的用来写项目的IDE。

**Comment by chenkovsky** [comment]
我用pycharm。
